server:
  port: 8082
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/openTalk?createDatabaseIfNotExist=true
    username: root
    password: 06121994

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.MySQL8Dialect
#app:
#  jwt:
#    secret: abcdefghijklmnOPQRSTUVWXYZ
#    cookiename: opentalk
